name: Docker Compose Action

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Execute tests in the running services
        run: |
          docker-compose exec web pytest
