name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        env:
          POSTGRES_DB: "django_db"
          POSTGRES_USER: "django_user"
          POSTGRES_PASSWORD: "django_pass"

      - name: Execute tests in the running services
        run: |
          docker compose exec web pytest
        # env:
        #   POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        #   POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        #   POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
